export const TRANSLATIONS = {
  en: { title: "Zen Arboretum", timeWarp: "Time Warp (600x)", realTime: "Real Time", rateDemo: "1 real sec = 10 game mins", rateNormal: "1 XP / Game Hour", status: "Current Status", level: "Level", max: "MAX", action: "Action Required!", water: "Water", pest: "Pest", feed: "Feed", peaceful: "Tree is growing peacefully...", welcome: "Welcome, {0}. Plant a seed and wait...", hourPassed: "One hour passed. The tree grew slightly naturally.", eventSoil: "The soil is dry! The tree needs water.", eventPest: "Beetles are eating the leaves!", eventPale: "The tree looks pale. It needs nutrients.", eventPrefix: "⚠️ EVENT:", resolved: "Event Resolved! Gained {0} XP.", fail: "That didn't help... The tree still needs attention!", levelUp: "🎉 LEVEL UP! Your tree is now Level {0}", maxLevel: "Your tree has reached its full potential!", langName: "EN", loginTitle: "Who is planting today?", loginPlaceholder: "Enter your name...", start: "Enter Garden", logout: "Switch User", usingServer: "Connected to server. Real-time saving active.", usingLocal: "Server unreachable. Using local storage.", selectUser: "Select User", createNew: "Create New User", back: "Back to List", collection: "Collection", locked: "Locked", unlocked: "Unlocked" },
  'zh-CN': { title: "禅意树圃", timeWarp: "时光飞逝 (600倍)", realTime: "实时模式", rateDemo: "1现实秒 = 10游戏分", rateNormal: "1 XP / 游戏小时", status: "当前状态", level: "等级", max: "最大", action: "需要采取行动！", water: "浇水", pest: "除虫", feed: "施肥", peaceful: "树木正在宁静地生长...", welcome: "欢迎, {0}。播下一颗种子，静静等待...", hourPassed: "一小时过去了。树木自然生长了一点。", eventSoil: "土壤干了！树需要水。", eventPest: "甲虫正在吃叶子！", eventPale: "树看起来很苍白。它需要养分。", eventPrefix: "⚠️ 事件：", resolved: "事件解决！获得了 {0} XP。", fail: "那没用... 树仍然需要照料！", levelUp: "🎉 升级了！你的树现在是等级 {0}", maxLevel: "你的树已经达到了潜力的巅峰！", langName: "简", loginTitle: "今天是谁在种植？", loginPlaceholder: "输入你的名字...", start: "进入花园", logout: "切换用户", usingServer: "已连接到服务器。实时保存已激活。", usingLocal: "无法连接服务器。使用本地存储。", selectUser: "选择用户", createNew: "新建用户", back: "返回列表", collection: "图鉴", locked: "未解锁", unlocked: "已解锁" },
  'zh-TW': { title: "禪意樹圃", timeWarp: "時光飛逝 (600倍)", realTime: "實時模式", rateDemo: "1現實秒 = 10遊戲分", rateNormal: "1 XP / 遊戲小時", status: "當前狀態", level: "等級", max: "最大", action: "需要採取行動！", water: "澆水", pest: "除蟲", feed: "施肥", peaceful: "樹木正在寧靜地生長...", welcome: "歡迎, {0}。播下一顆種子，靜靜等待...", hourPassed: "一小時過去了。樹木自然生長了一點。", eventSoil: "土壤乾了！樹需要水。", eventPest: "甲蟲正在吃葉子！", eventPale: "樹看起來很蒼白。它需要養分。", eventPrefix: "⚠️ 事件：", resolved: "事件解決！獲得了 {0} XP。", fail: "那沒用... 樹仍然需要照料！", levelUp: "🎉 升級了！你的樹現在是等級 {0}", maxLevel: "你的樹已經達到了潛力的巔峰！", langName: "繁", loginTitle: "今天是用誰在種植？", loginPlaceholder: "輸入你的名字...", start: "進入花園", logout: "切換用戶", usingServer: "已連接到服務器。實時保存已激活。", usingLocal: "無法連接服務器。使用本地存儲。", selectUser: "選擇用戶", createNew: "新建用戶", back: "返回列表", collection: "圖鑑", locked: "未解鎖", unlocked: "已解鎖" }
};

export const createTranslator = (lang) => (key, ...args) => {
  let str = TRANSLATIONS[lang][key] || key;
  args.forEach((arg, i) => { str = str.replace(`{${i}}`, arg); });
  return str;
};
